# Generated by Django 3.0.5 on 2020-07-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ign', models.CharField(max_length=50)),
                ('quote', models.CharField(max_length=100)),
                ('character', models.CharField(choices=[('Bangalore', 'Bangalore'), ('Bloodhound', 'Bloodhound'), ('Caustic', 'Caustic'), ('Crypto', 'Crypto'), ('Gibralter', 'Gibralter'), ('Lifeline', 'Lifeline'), ('Loba', 'Loba'), ('Mirage', 'Mirage'), ('Octance', 'Octance'), ('Pathfinder', 'Pathfinder'), ('Revenant', 'Revenant'), ('Wattson', 'Wattson'), ('Wraith', 'Wraith')], default='Mirage', max_length=15)),
                ('content', models.TextField()),
            ],
        ),
    ]
