# Generated by Django 3.0.5 on 2020-07-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='profilePicture',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
