# Generated by Django 3.0.5 on 2020-07-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_teammember_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='profilePicture',
            field=models.ImageField(default='default.jpg', upload_to='teamPictures'),
        ),
    ]
