# Generated by Django 3.0.5 on 2020-07-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200704_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
