# Generated by Django 3.0.5 on 2020-07-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200704_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
